import QRCode from 'qrcode';
import { PHASES, type Meta, type PlayersResponse, type RawPixel, type StatsResponse, type LeaderboardResponse, type Player } from '../../../shared/types.js';
import { Api, ApiFailure, poll } from '../shared/api';
import { adminKey, config, playUrl, scope } from '../shared/config';
import { Wall } from '../shared/canvas';
import { button, el, json, message, time, ttlTime } from '../shared/ui';
import { scenes } from './slides';
import { examplePlayer, examplePixel, exampleStats } from './static';
import { Meter, Inspector, Leaderboard } from './widgets';
export function startStage(root:HTMLElement,api:Api){
  let meta:Meta|undefined,stats:StatsResponse|undefined,players:PlayersResponse={players:[],total:0},index=Number(sessionStorage.getItem(`scene:${scope}`)||0),busy=false,rawPixel:RawPixel|undefined,rawPlayer:Player|undefined,starting=false;
  index=Math.max(0,Math.min(scenes.length-1,index));
  const shell=el('main','stage'),header=el('header','stage-header'),status=el('span','status'),scene=el('section','scene'),footer=el('footer','stage-footer'),notice=el('p','notice'),widgets=el('div','widgets');notice.setAttribute('role','status');
  const meter=new Meter(),inspector=new Inspector(),lb=new Leaderboard(),wall=new Wall(api,()=>meta,true),timer=el('span','timer'),hover=el('span','mono'),names=el('div','names'),raw=el('div','raw-items'),teams=el('div','team-bar'),ttl=el('span','ttl mono');
  lb.onchanges=changes=>{inspector.feed.push(...changes);inspector.feed=inspector.feed.slice(-20);};
  const showError=(error:unknown)=>{notice.textContent=message(error);};
  header.append(el('span','brand','DynamoLive'),el('span','eyebrow','UNA TABELLA. I VOSTRI DATI.'),status);
  const settings=button('Regia',()=>settingsDialog());header.append(settings);
  footer.append(button('←',()=>navigate(index-1)),el('span','progress'),button('→',()=>navigate(index+1)),button('X-Ray · I',()=>{inspector.visible=!inspector.visible;inspector.update(api);}),button('Costo · M',()=>{meter.expanded=!meter.expanded;meter.update(stats);}),button('Tema',()=>document.documentElement.classList.toggle('paper')));
  widgets.append(meter.node,inspector.node);shell.append(header,scene,widgets,notice,footer);root.append(shell);
  wall.onhover=value=>{hover.textContent=value;};
  wall.onselect=async(x,y)=>{if(config.static)return;try{const {serverTime:pixelTime,_inspect:pixelInspect,...pixelItem}=await api.call<RawPixel>(`/pixel/${x}/${y}`);rawPixel=pixelItem;updateRaw();if(scenes[index].id!=='you'){const modal=el('dialog','raw-dialog');modal.append(json(rawPixel),button('Escludi autore',async()=>{await action('/admin/ban',{pid:rawPixel!.byId});modal.close();}),button('Chiudi',()=>modal.close()));shell.append(modal);modal.showModal();modal.onclose=()=>modal.remove();}}catch(e){showError(e);}};
  function updateRaw(){raw.replaceChildren();const selector=el('select');selector.setAttribute('aria-label','Giocatore da mostrare');selector.append(new Option('Scegli uno spettatore',''));players.players.forEach(p=>selector.append(new Option(p.nickname,p.pid)));if(rawPlayer)selector.value=rawPlayer.pid;selector.onchange=async()=>{if(!selector.value||config.static)return;try{const {serverTime:playerTime,_inspect:playerInspect,...playerItem}=await api.call<Player>(`/player/${selector.value}`);rawPlayer=playerItem;updateRaw();}catch(e){showError(e);}};
    const a=el('div'),b=el('div');a.append(selector,rawPlayer?json(rawPlayer):el('p','muted','Seleziona un giocatore reale.'));b.append(rawPixel?json(rawPixel):el('p','muted','Seleziona un pixel sulla tela.'));raw.append(a,b);
  }
  async function action(path:string,body:unknown){if(config.static){notice.textContent='Fallback statico: comandi API disabilitati.';return;}try{const response=await api.call<any>(path,body);if(response.phase)meta=response;await wall.refresh(true);notice.textContent='Comando applicato';}catch(e){if(e instanceof ApiFailure&&e.status===409)meta=await api.call<Meta>('/meta');showError(e);} }
  async function phase(target:typeof PHASES[number]){if(!meta)throw Error('Attendere META prima di avanzare');const current=PHASES.indexOf(meta.phase),next=PHASES.indexOf(target);if(next<=current)return;if(next!==current+1)throw Error('Segui le scene in ordine per cambiare fase. I salti sono solo visuali.');meta=await api.call<Meta>('/admin/phase',{phase:target,expectedVersion:meta.version});}
  async function navigate(next:number,jump=false){if(next<0||next>=scenes.length||busy||starting)return;busy=true;
    try{if(!config.static&&!jump&&next===index+1&&scenes[next].id!=='hotkey')await phase(scenes[next].phase);index=next;sessionStorage.setItem(`scene:${scope}`,String(index));render();}catch(e){if(e instanceof ApiFailure&&e.status===409)meta=await api.call<Meta>('/meta');showError(e);}finally{busy=false;}}
  async function qr(url:string){const container=el('div','qr'),canvas=el('canvas');await QRCode.toCanvas(canvas,url,{width:300,margin:3,color:{dark:'#0B0D10',light:'#FFFFFF'},errorCorrectionLevel:'M'});canvas.setAttribute('aria-label',`QR: ${url}`);const link=el('a','mono',url);link.href=url;container.append(canvas,link);return container;}
  function diagram(file:string,alt:string){const img=el('img','diagram');img.src=`/${file}.svg`;img.alt=alt;return img;}
  function render(){const s=scenes[index];shell.dataset.scene=s.id;scene.replaceChildren(el('p','eyebrow',`${s.number?`SLIDE ${String(s.number).padStart(2,'0')}`:'LIVE EXPERIENCE'} / ${s.time}`),el('h1','',s.title));footer.querySelector('.progress')!.textContent=`${index+1} / ${scenes.length}`;
    meter.expanded=s.id==='cost';inspector.visible=s.id==='hotkey';meter.update(stats);inspector.update(api);
    if(s.id==='lobby'){const holder=el('div','join-stage');scene.append(holder,names);void qr(playUrl()).then(q=>holder.append(q));}
    if(s.id==='pixel'){scene.append(timer,wall.canvas,hover,el('p','prompt',meta?.prompt||'Scrivete DDB'));void wall.refresh(true).catch(showError);}
    if(s.id==='history')scene.append(diagram('history','Traffico illustrativo, non una misura storica'),el('p','mono','Dynamo 2007 → DynamoDB 2012'));
    if(s.id==='you'){scene.append(raw,wall.canvas);wall.canvas.classList.add('compact');updateRaw();void wall.refresh(true).catch(showError);}else wall.canvas.classList.remove('compact');
    if(s.id==='keys'){scene.append(diagram('keys','Gruppi logici SESSION e CANVAS, non partizioni fisiche'),el('p','muted','Gruppi logici ≠ partizioni fisiche'),names);}
    if(s.id==='patterns')scene.append(diagram('patterns','Domande, chiavi e indici: ByTime e ByScore'));
    if(s.id==='architecture')scene.append(diagram('architecture','Telefono, HTTP API, Lambda, DynamoDB'));
    if(s.id==='hotkey'){scene.append(timer,teams,lb.node);if(meta?.phase==='hotkey_ready'&&!config.static)scene.append(button('Avvia 3 · 2 · 1',async()=>{if(starting||config.static)return;starting=true;try{for(let n=3;n>0;n--){timer.textContent=String(n);await new Promise(r=>setTimeout(r,1000));}await phase('hotkey_running');render();}catch(e){showError(e);}finally{starting=false;}},'primary'));}
    if(s.id==='choice'){const columns=el('div','choice');columns.append(el('div','','Sì\nAccessi noti\nTraffico variabile'),el('div','','No\nQuery ad hoc\nAnalytics'));scene.append(columns);}
    if(s.id==='end'){scene.append(wall.canvas,el('p','muted','Scadenza logica · cancellazione AWS asincrona'),ttl);const holder=el('div','document-qr');scene.append(holder);void qr(new URL(config.document,import.meta.env.VITE_PUBLIC_ORIGIN||location.origin).href).then(q=>holder.append(q));void wall.refresh(true).catch(showError);}
  }
  function settingsDialog(){const dialog=el('dialog','settings');dialog.append(el('h2','','Regia della sessione'));
    const form=el('form'),key=el('input'),apiInput=el('input'),sid=el('input');key.type='password';key.placeholder='Chiave admin';key.value=api.admin;key.autocomplete='off';key.setAttribute('aria-label','Chiave admin');apiInput.value=config.api;apiInput.setAttribute('aria-label','Base API');sid.value=config.sid;sid.setAttribute('aria-label','Session ID');
    const submit=el('button','primary','Applica');submit.type='submit';form.append(el('label','','Chiave admin (solo sessione)'),key,el('label','','Base API'),apiInput,el('label','','Session ID'),sid,submit);
    form.onsubmit=e=>{e.preventDefault();api.admin=key.value;sessionStorage.setItem(adminKey,key.value);if(apiInput.value!==config.api||sid.value!==config.sid){const url=new URL(location.href);url.searchParams.set('api',apiInput.value);url.searchParams.set('s',sid.value);location.assign(url.href);}else{dialog.close();notice.textContent='Chiave applicata';}};
    dialog.append(form,button('Crea questa sessione (solo sid nuovo)',async()=>{await action('/admin/reset',{});dialog.close();}),button('Congela · F',()=>action('/admin/phase',{phase:'pixel_frozen',expectedVersion:meta?.version})),button('Nascondi / mostra · H',()=>action('/admin/hide',{hidden:!meta?.canvasHidden})),button('Cancella selezione · Shift+C',()=>clear()),button('Bot · B',()=>action('/admin/bots',{enabled:!meta?.botsEnabled})),el('p','muted','Bot: avvia prima il runner esterno. Selezione: clic iniziale e Shift+clic finale sulla tela congelata.'),button('Locale · L',()=>local()),button('Fallback statico',()=>{const url=new URL(location.href);url.searchParams.set('mode','static');location.assign(url.href);}),button('Video · P',()=>backup()),button('Chiudi',()=>dialog.close()));shell.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();
  }
  async function clear(){if(!wall.rectangle){notice.textContent='Seleziona il rettangolo con clic e Shift+clic.';return;}if(meta?.phase==='pixel'){notice.textContent='Prima congela la tela con F.';return;}await action('/admin/clear',wall.rectangle);}
  function local(){const url=new URL(location.href);url.searchParams.set('api',import.meta.env.VITE_LOCAL_API||'local');url.searchParams.set('s',import.meta.env.VITE_LOCAL_SESSION||'prova-01');url.searchParams.delete('mode');location.assign(url.href);}
  function backup(){const dialog=el('dialog','backup'),video=el('video');video.controls=true;video.src=config.backup;video.onloadeddata=()=>{void video.play();};video.onerror=()=>{dialog.append(el('p','notice','Video non disponibile. Registralo dopo la prova integrata e copialo in public/backup.mp4.'));};dialog.append(video,button('Chiudi',()=>dialog.close()));shell.append(dialog);dialog.showModal();dialog.onclose=()=>{video.pause();dialog.remove();};}
  document.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&(e.target.matches('input,textarea,select')||e.target.isContentEditable)||document.querySelector('dialog[open]'))return;
    if(e.key==='ArrowRight'){e.preventDefault();void navigate(index+1);}else if(e.key==='ArrowLeft'){e.preventDefault();void navigate(index-1);}else if(/^[1-8]$/.test(e.key))void navigate(scenes.findIndex(s=>s.number===+e.key),true);
    else if(e.key.toLowerCase()==='i'){inspector.visible=!inspector.visible;inspector.update(api);}else if(e.key.toLowerCase()==='m'){meter.expanded=!meter.expanded;meter.update(stats);}
    else if(e.key.toLowerCase()==='f'&&meta?.phase==='pixel')void action('/admin/phase',{phase:'pixel_frozen',expectedVersion:meta.version});
    else if(e.key.toLowerCase()==='h')void action('/admin/hide',{hidden:!meta?.canvasHidden});else if(e.key==='C'&&e.shiftKey)void clear();
    else if(e.key.toLowerCase()==='b')void action('/admin/bots',{enabled:!meta?.botsEnabled});else if(e.key.toLowerCase()==='l')local();else if(e.key.toLowerCase()==='p')backup();});
  if(!config.static){
    poll(async()=>{const previous=meta?.phase;meta=await api.call<Meta>('/meta');status.textContent=`${config.mock?'DEMO · SIMULATO':'LIVE'} · ${config.sid} · ${meta.phase}`;if(previous!==meta.phase&&scenes[index].id==='hotkey')render();wall.draw();},1500,showError);
    poll(async()=>{if(!api.admin&&!config.mock)return;players=await api.call<PlayersResponse>('/players');names.replaceChildren(...players.players.slice(0,60).map(p=>el('span',meta?.teamsRevealed?`name ${p.team}`:'name',p.nickname)));},2000,showError);
    poll(async()=>{if(!api.admin&&!config.mock)return;stats=await api.call<StatsResponse>('/stats');meter.update(stats);const total=stats.teamOrange+stats.teamPurple;teams.replaceChildren(el('span','orange',`${stats.teamOrange} · ARANCIONE`),el('span','purple',`VIOLA · ${stats.teamPurple}`));teams.style.setProperty('--orange',`${total?stats.teamOrange/total*100:50}%`);},1000,showError);
    poll(async()=>{if(!meta)return;if(['pixel','you','end'].includes(scenes[index].id)){const cursor=wall.state.cursor;await wall.refresh();const changes=[...wall.state.pixels.values()].filter(p=>p.t>cursor);inspector.feed.push(...changes.map(p=>`${p.by} → (${p.x},${p.y})`));inspector.feed=inspector.feed.slice(-20);}inspector.update(api);},500,showError);
    poll(async()=>{if(meta?.roundId){const data=await api.call<LeaderboardResponse>('/leaderboard');lb.update(data);}},1000,showError);
  }else{status.textContent='FALLBACK STATICO · ESEMPI SIMULATI';meta={sid:config.sid,phase:'end',version:1,phaseStartedAt:0,phaseEndsAt:null,canvasW:48,canvasH:27,cooldownMs:1500,roundMs:15000,pixelMs:90000,canvasHidden:false,canvasRevision:0,teamsRevealed:true,roundId:null,roundStartedAt:null,roundEndsAt:null,tapGraceMs:2000,expiresAt:0,prompt:'Scrivete DDB',botsEnabled:false};
    stats=exampleStats;rawPlayer=examplePlayer;rawPixel=examplePixel;players={players:[examplePlayer],total:1};names.append(el('span','name','Esempio simulato'));lb.update({top:[{nickname:'Esempio',team:'orange',score:87,rank:1}],provisional:false,roundId:null});teams.append(el('span','orange','2000 · ARANCIONE'),el('span','purple','VIOLA · 1800'));teams.style.setProperty('--orange','53%');
    for(let x=8;x<40;x++)for(let y=8;y<19;y++)if((x+y)%3===0)wall.state.pixels.set(`${x},${y}`,{x,y,c:2,by:'Esempio statico',t:0});wall.refresh=async()=>{wall.draw();};}
  setInterval(()=>{if(!meta)return;if(meta.expiresAt>0&&meta.expiresAt*1000<=api.now()){wall.state.pixels.clear();wall.draw();status.textContent='SESSIONE SCADUTA';}if(!starting)timer.textContent=meta.phaseEndsAt?time(meta.phaseEndsAt-api.now()):meta.phase==='hotkey_end'?'PODIO':'';ttl.textContent=config.static?'TTL · Esempio statico':ttlTime(meta.expiresAt*1000-api.now());if(!api.online)status.textContent='RETE ASSENTE · RICONNESSIONE';},100);
  window.addEventListener('online',()=>{void wall.refresh(true).catch(showError);});render();
  if(!api.admin&&!config.mock&&!config.static)settingsDialog();
}
