import assert from 'node:assert/strict';
import { BotClient, sleep } from '../bots/client.js';
import { BotGroup } from '../bots/games.js';
import type { Meta, StatsResponse } from '../shared/types.js';
const sid=`smoke-${Date.now()}`,api='http://127.0.0.1:3001';
if(!process.env.ADMIN_KEY)throw Error('Set ADMIN_KEY via .env');
const client=new BotClient(api,sid),admin={'x-admin-key':process.env.ADMIN_KEY};
const phase=async(phase:string)=>{const m=await client.meta();return client.request<Meta>('/admin/phase',{phase,expectedVersion:m.version},admin);};
await client.request('/admin/reset',{roundMs:1000,pixelMs:5000},admin);
const bots=new BotGroup(client,3);
await bots.step(await client.meta());
await phase('pixel');await bots.step(await client.meta());
await phase('pixel_frozen');await phase('talk');await phase('hotkey_ready');await phase('hotkey_running');
await bots.step(await client.meta());
await sleep(3100);
assert.equal((await client.meta()).phase,'hotkey_end');await phase('end');
const stats=await client.request<StatsResponse>('/stats',undefined,admin);
assert.equal(stats.playersJoined,3);assert.equal(stats.pixelsPlaced,3);assert.ok(stats.taps>=6);
assert.equal(stats.teamOrange+stats.teamPurple,stats.taps);
const denied=await fetch(`${api}/s/${sid}/meta`,{headers:{origin:'https://untrusted.example'}});assert.equal(denied.status,403);
const malformed=await fetch(`${api}/s/${sid}/join`,{method:'POST',headers:{'content-type':'application/json'},body:'{'});assert.equal(malformed.status,400);
console.log(`HTTP + bots OK: ${sid}; ${stats.playersJoined} players, ${stats.pixelsPlaced} pixels, ${stats.taps} taps. No cloud requests.`);
